version: "3.9"

services:
  auth-service:
    build: ./auth
    ports:
      - "8001:8000"

  user-service:
    build: ./user
    ports:
      - "8002:8000"

  product-service:
    build: ./product
    ports:
      - "8003:8000"

  order-service:
    build: ./order
    ports:
      - "8004:8000"

  chat-service:
    build: ./chat
    ports:
      - "8005:8000"