services:
  frontend:
    build: ./frontend
    container_name: sre_frontend
    ports:
      - "8080:80"
  product-service:
    build: ./product-service
    container_name: sre_product_service
    ports:
      - "8001:8000"
  order-service:
    build: ./order-service
    container_name: sre_order_service
    ports:
      - "8002:8000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
  auth-service:
    build: ./auth-service
    container_name: sre_auth_service
    ports:
      - "8003:8000"
  user-service:
    build: ./user-service
    container_name: sre_user_service
    ports:
      - "8004:8000"
  chat-service:
    build: ./chat-service
    container_name: sre_chat_service
    ports:
      - "8005:8000"

  nginx:
    image: nginx:latest
    container_name: sre_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - product-service
      - order-service
      - auth-service
      - user-service
      - chat-service
  db:
    image: postgres:15
    container_name: sre_postgres
    environment:
      POSTGRES_USER: sre_user
      POSTGRES_PASSWORD: sre_password
      POSTGRES_DB: sre_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus
    container_name: sre_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - product-service
      - order-service
  grafana:
    image: grafana/grafana
    container_name: sre_grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

volumes:
  postgres_data: