events {}

http {
    resolver 127.0.0.11 valid=30s;

    server {
        listen 80;

        # Frontend
        location / {
            proxy_pass http://sre_frontend:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Product Service
        location /api/products/ {
            proxy_pass http://sre_product_service:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Order Service
        location /api/orders/ {
            proxy_pass http://sre_order_service:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Auth Service
        location /api/auth/ {
            proxy_pass http://sre_auth_service:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # User Service
        location /api/users/ {
            proxy_pass http://sre_user_service:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Chat Service
        location /api/chat/ {
            proxy_pass http://sre_chat_service:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Grafana
        location /grafana/ {
            proxy_pass http://sre_grafana:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}